require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'lib/generators/migration_guard/install/templates/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rails-migration-guard.gemspec'
    - 'lib/tasks/migration_guard.rake'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

RSpec/ExampleLength:
  Max: 15

RSpec/FilePath:
  Exclude:
    - 'spec/generators/**/*'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/generators/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

Layout/LineLength:
  Max: 120

Naming/PredicateMethod:
  Exclude:
    - 'lib/migration_guard/configuration.rb'
    - 'lib/migration_guard/rake_tasks.rb'

Rails/ApplicationRecord:
  Exclude:
    - 'lib/migration_guard/migration_guard_record.rb'