plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'lib/generators/migration_guard/install/templates/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rails-migration-guard.gemspec'
    - 'lib/tasks/migration_guard.rake'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - 'spec/integration/**/*'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/generators/**/*'

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/lib/migration_guard/rake_tasks_spec.rb'
    - 'spec/generators/migration_guard/hooks_generator_spec.rb'

RSpec/NestedGroups:
  Max: 4

Layout/LineLength:
  Max: 120

Naming/PredicateMethod:
  Exclude:
    - 'lib/migration_guard/configuration.rb'
    - 'lib/migration_guard/rake_tasks.rb'

Rails/ApplicationRecord:
  Exclude:
    - 'lib/migration_guard/migration_guard_record.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/tasks/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'
    - 'spec/integration/**/*'

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/lib/migration_guard/branch_change_detector_spec.rb'
    - 'spec/integration/branch_switching_spec.rb'

