# GitHub Pages configuration for Rails Migration Guard
title: "Rails Migration Guard"
description: "Intelligent migration tracking for Rails applications"
url: "https://tommy2118.github.io"
baseurl: "/rails-migration-guard"

# Build settings
markdown: kramdown
highlighter: rouge
theme: null
plugins: []

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Quick Start"
    url: "/quick-start.html"
  - title: "Documentation"
    url: "/docs/"
  - title: "Installation"
    url: "/installation/"
  - title: "Configuration"
    url: "/configuration.html"
  - title: "Examples"
    url: "/examples/"
  - title: "Team Collaboration"
    url: "/team-collaboration.html"
  - title: "Troubleshooting"
    url: "/troubleshooting.html"
  - title: "GitHub"
    url: "https://github.com/tommy2118/rails-migration-guard"
    external: true

# SEO
social:
  name: Rails Migration Guard
  links:
    - https://github.com/tommy2118/rails-migration-guard

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md
