name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']
        rails-version: ['6.1', '7.0', '7.1', '7.2', '8.0']
        exclude:
          # Rails 8.0 requires Ruby 3.2+
          - ruby-version: '3.1'
            rails-version: '8.0'

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Run linter
      run: bundle exec rubocop